# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: thsummer/wrfchem:v4.5.1
      options: --cpus 2

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Create domain directory
        run: |
          cd /root/wrf
          mkdir domain && cd domain
          mkdir testMetgridParallel && cd testMetgridParallel
          cp $GITHUB_WORKSPACE/data/* ./

      - name: copy intermediate FILE
        run: |
          cd
          mkdir Data && cd Data
          mkdir tutorialFILE && cd tutorialFILE
          wget https://www2.mmm.ucar.edu/wrf/TUTORIAL_DATA/single_domain/FILE.tar.gz
          tar -xvzf FILE.tar.gz

      - name: install python packages
        run: |
          cd $GITHUB_WORKSPACE
          mkdir .venv
          virtualenv .venv
          chmod +x .venv/bin/activate
          .venv/bin/activate
          .venv/bin/pip install netCDF4 psutil pytest

      - name: test script
        run: |
          cd $GITHUB_WORKSPACE/test
          source $GITHUB_WORKSPACE/.venv/bin/activate
          ./test_parallel.py
